In [25]:
import numpy as np  # linear algebra 
import pandas as pd # data preprocessing

In [26]:
df = pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [27]:
# Ine review
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

 Text Cleaning 
1. Sample 10000 rows
2. Remove html tags
3. Remove special characters
4. Converting every thing to lower case
5. Removing Stop Words
6. Stemming

In [28]:
df = df.sample(10000)

In [29]:
df.shape

(10000, 2)

In [30]:
# NO missing value lies
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 24811 to 16443
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB

In [31]:
df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

C:\Users\its\AppData\Local\Temp\ipykernel_16760\4240984564.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sentiment'].replace({'positive':1,'negative':0},inplace=True)
C:\Users\its\AppData\Local\Temp\ipykernel_16760\4240984564.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

In [37]:
df.head()

                                                  review  sentiment
24811  I haven't laughed that much in a long time - a...          1
29438  The reviewer who called this movie a bust has ...          1
22033  Instead of writing a paragraph, I'll give four...          1
15146  The story of Ned Kelly has been enshrouded in ...          1
39121  Hmm, is it right to compare Tiffani Thiessen a...          1

In [38]:
import re
clean = re.compile('<.*?>')
re.sub(clean,'',df.iloc[2].review)

'Instead of writing a paragraph, I\'ll give four good reasons why 2001 is the greatest cinema experience of all time: 1) It is a visual Odyssey that could only be told on the big screen. The special effects that won Kubrick his only Oscar are the most stunning effects before that age of Jurassic Park and T2. They allow Kubrick to give an accurate (or at least are the most accurate) depiction of space travel to date. The silence that fills the space scenes not only serves its purpose as accurate science, but also adds to the mood of the film (to be discussed in a later point with HAL). The fact that Kubrick shot the moon scenes before the Apollo landing is a gutsy yet fulfilling move. Many have said that upon its original release, it was a favorite "trip" movie. I can think of no other movie that has such amazing visuals for its time and even of all time (sorry Phantom Menace fans!) 2) Kubrick\'s directing style is terrific. As in all his films, Kubrick likes to use his camera as means to delve into the psychology of his characters and plots. His camera is not as mobile as other greats, such as Scorsese, but instead sits and watches the narrative unfold. Faces are the key element of a Kubrick film. Like classic movies, such as M and Touch of Evil, Kubrick focuses on the characters\' faces to give the audience a psychological view-point. Even he uses extreme close-ups of HAL\'s glowing red "eye" to show the coldness and determination of the computerizd villain. I could go on, but in summation Kubrick is at the hieght of his style. 3) HAL 9000 is one of the most villainous characters in film history. I whole-heartedly agree with the late Gene Siskle\'s opinion of HAL 9000. Most of this film takes place in space. Through the use of silence and the darkness of space itself, a mood of isolation is created. Dave and his crewmen are isolated between earth and jupiter, with nowhere to escape. Combine this mood with the cold, calculated actions of HAL 9000 and you have the most fearful villain imaginable. I still, although having see this film several times, feel my chest tighten in a particular scene. 4) The controversial ending of 2001 always turns people away from this film. Instead of trying to give my opinion of the what it means and what my idea of 2001\'s meaning in general is, I\'d like to discuss the fact that the ending serves to leave the movie open-ended. Kubrick has stated that he inteded to make 2001 open for discussion. He left its meaning in the hands of the viewer. By respecting the audience\'s intelligence, Kubrick allowed his movie to be the beginning, not the end, of a meaningful discussion on man\'s past, present, and future. The beauty of 2001 is that the ending need not mean anything deep, it can just be a purely plot driven explanation and the entire movie can be viewed as an entertaining journey through space. No other movie, save the great Citizen Kane, leaves itself open to discussion like 2001. It is truly meant to be a surreal journey that involves not only the eye but the mind. Instead of waiting in long lines for the Phantom Menace, rent a widescreen edition of 2001 and enjoy the greatest cinematic experience.'

In [39]:
# Function to clean html tags
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean,'',text)

In [40]:
df['review'] = df['review'].apply(clean_html)

In [41]:
# Converting everything to lower

def convert_lower(text):
    return text.lower()

In [42]:
df['review'] = df['review'].apply(convert_lower)

In [43]:
# function to remove special character
def remove_special(text):
    x=''

    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x + ' '
    return x

In [44]:
df['review'] = df['review'].apply(remove_special)

In [48]:
# Remove the step words
# It is natural language toolkit Library
import nltk

In [49]:
from nltk.corpus import stopwords

In [50]:
df

                                                  review  sentiment
24811  i haven t laughed that much in a long time   a...          1
29438  the reviewer who called this movie a bust has ...          1
22033  instead of writing a paragraph  i ll give four...          1
15146  the story of ned kelly has been enshrouded in ...          1
39121  hmm  is it right to compare tiffani thiessen a...          1
...                                                  ...        ...
11661    may contain spoilers  a dude in a dopey look...          0
5511   this is an atrocious movie  two demented young...          0
27842  for a film that s ostensibly about sex and lea...          1
19770  although i was in this movie playing the part ...          1
16443  sometimes  changes to novels when they re made...          0

[10000 rows x 2 columns]

In [59]:
from nltk.corpus import stopwords
sw = set(stopwords.words('english'))

def remove_stopwords(text):
    return [word for word in text.split() if word not in sw]

In [60]:
df['review'] = df['review'].apply(remove_stopwords)

In [61]:
df

                                                  review  sentiment
24811  [laughed, much, long, time, although, movie, s...          1
29438  [reviewer, called, movie, bust, clearly, misse...          1
22033  [instead, writing, paragraph, give, four, good...          1
15146  [story, ned, kelly, enshrouded, myth, exaggera...          1
39121  [hmm, right, compare, tiffani, thiessen, mark,...          1
...                                                  ...        ...
11661  [may, contain, spoilers, dude, dopey, looking,...          0
5511   [atrocious, movie, two, demented, young, women...          0
27842  [film, ostensibly, sex, leather, right, oddly,...          1
19770  [although, movie, playing, part, sheriff, hodg...          1
16443  [sometimes, changes, novels, made, films, nece...          0

[10000 rows x 2 columns]

In [63]:
# Perform Stemming
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [65]:
 y =[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z = y[:]
    y.clear()
    return z

In [66]:
stem_words(['I','loved','loving','it'])

['i', 'love', 'love', 'it']

In [67]:
df['review']= df['review'].apply(stem_words)

In [69]:
df

                                                  review  sentiment
24811  [laugh, much, long, time, although, movi, sad,...          1
29438  [review, call, movi, bust, clearli, miss, poin...          1
22033  [instead, write, paragraph, give, four, good, ...          1
15146  [stori, ned, kelli, enshroud, myth, exagger, t...          1
39121  [hmm, right, compar, tiffani, thiessen, mark, ...          1
...                                                  ...        ...
11661  [may, contain, spoiler, dude, dopey, look, kon...          0
5511   [atroci, movi, two, dement, young, women, sedu...          0
27842  [film, ostens, sex, leather, right, oddli, swe...          1
19770  [although, movi, play, part, sheriff, hodg, st...          1
16443  [sometim, chang, novel, made, film, necessari,...          0

[10000 rows x 2 columns]

In [73]:
# Join back
def join_back(list_input):
    return " ".join(list_input)

In [74]:
df['review'] = df['review'].apply(join_back)

In [75]:
df['review']

24811    laugh much long time although movi sad moment ...
29438    review call movi bust clearli miss point obvio...
22033    instead write paragraph give four good reason ...
15146    stori ned kelli enshroud myth exagger time han...
39121    hmm right compar tiffani thiessen mark paul go...
                               ...
11661    may contain spoiler dude dopey look kong suit ...
5511     atroci movi two dement young women seduc tortu...
27842    film ostens sex leather right oddli sweet stor...
19770    although movi play part sheriff hodg still man...
16443    sometim chang novel made film necessari good t...
Name: review, Length: 10000, dtype: object

In [76]:
x = df.iloc[:,0:1].values

In [77]:
x.shape

(10000, 1)

In [82]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [83]:
x = cv.fit_transform(df['review']).toarray()

In [84]:
x.shape

(10000, 35874)

In [87]:
x[0].mean()

np.float64(0.001338016390700786)

In [88]:
y = df.iloc[:,-1].values

In [89]:
y.shape

(10000,)

In [ ]:
# x,y
# Training Set
# Testing Set

In [90]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [94]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 35874)
(2000, 35874)
(8000,)
(2000,)

In [95]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [96]:
cf1 = GaussianNB()
cf2 = MultinomialNB()
cf3 = BernoulliNB()

In [97]:
cf1.fit(x_train,y_train)
cf2.fit(x_train,y_train)
cf3.fit(x_train,y_train)

BernoulliNB()

In [99]:
y_pred1 = cf1.predict(x_test)
y_pred2 = cf2.predict(x_test)
y_pred3 = cf3.predict(x_test)

In [100]:
y_pred1.shape

(2000,)

In [101]:
from sklearn.metrics import accuracy_score

In [102]:
print('Guassian',accuracy_score(y_test,y_pred1))
print('Multinomial',accuracy_score(y_test,y_pred2))
print('Bernaulli',accuracy_score(y_test,y_pred3))

Guassian 0.6345
Multinomial 0.837
Bernaulli 0.846